from __future__ import annotations

__version__ = "0.1.0"

from .config import (
    AppConfig,
    load_config,
    load_config_with_env_file,
    load_env_file,
    normalise_log_level,
    normalise_scrape_mode,
    parse_bool,
    parse_non_negative_int,
    parse_positive_float,
    parse_positive_int,
)
from .contact_cleaner import (
    CleanedPhoneNumber,
    normalise_phone_candidate,
    validate_phone_candidate,
)
from .batch import (
    BatchFailure,
    BatchResult,
    OrganisationInput,
    ParsedOrganisationRow,
    analyse_organisation,
    export_batch_failures,
    normalise_column_name,
    read_organisations_csv,
    read_parsed_organisations_csv,
    run_batch_analysis,
)
from .crawler import (
    CrawlFailure,
    CrawledWebsite,
    crawl_website,
    normalise_crawl_url,
)
from .dashboard import (
    DashboardSummary,
    SignalCount,
    build_dashboard_summary,
    format_dashboard,
    print_dashboard,
)
from .dynamic_scraper import (
    DynamicPageOptions,
    DynamicScrapeResult,
    DynamicScraperError,
    scrape_dynamic_page,
    seconds_to_milliseconds,
    validate_css_selector,
)
from .demo_data import (
    build_demo_dashboard_records,
    build_demo_export_evidence,
    build_demo_export_records,
    print_demo_dashboard,
    run_demo_export,
)
from .exporter import (
    LeadRecord,
    build_lead_record,
    export_leads_to_excel,
)
from .logging_config import configure_logging
from .link_prioritiser import (
    LinkPriority,
    normalise_link_text,
    prioritise_links,
    score_link,
)
from .scorer import (
    LeadScore,
    ScoreBreakdownItem,
    build_score_summary,
    classify_priority,
    score_lead,
)
from .resource_filter import (
    ResourceClassification,
    classify_content_type,
    classify_resource_url,
    extract_url_extension,
)
from .scrape_strategy import (
    ScrapeDecision,
    scrape_with_strategy,
    static_page_appears_insufficient,
)
from .signal_detector import (
    DetectedSignals,
    SignalEvidence,
    create_excerpt,
    detect_signals_from_pages,
    detect_signals_in_text,
    normalise_text,
)
from .static_scraper import (
    DiscoveredLink,
    DownloadedPage,
    ScrapedPage,
    UnsupportedContentError,
    calculate_retry_delay,
    download_page_response,
    is_retryable_exception,
    parse_page,
    scrape_page,
)


__all__ = [
    "__version__",
    "AppConfig",
    "BatchFailure",
    "BatchResult",
    "CleanedPhoneNumber",
    "CrawlFailure",
    "CrawledWebsite",
    "DashboardSummary",
    "DetectedSignals",
    "DiscoveredLink",
    "DownloadedPage",
    "DynamicPageOptions",
    "DynamicScrapeResult",
    "DynamicScraperError",
    "LeadRecord",
    "LeadScore",
    "LinkPriority",
    "OrganisationInput",
    "ParsedOrganisationRow",
    "ResourceClassification",
    "ScrapedPage",
    "ScrapeDecision",
    "ScoreBreakdownItem",
    "SignalCount",
    "SignalEvidence",
    "UnsupportedContentError",
    "analyse_organisation",
    "build_dashboard_summary",
    "build_demo_dashboard_records",
    "build_demo_export_evidence",
    "build_demo_export_records",
    "build_lead_record",
    "build_score_summary",
    "classify_priority",
    "classify_content_type",
    "classify_resource_url",
    "configure_logging",
    "create_excerpt",
    "crawl_website",
    "calculate_retry_delay",
    "detect_signals_from_pages",
    "detect_signals_in_text",
    "download_page_response",
    "export_batch_failures",
    "export_leads_to_excel",
    "extract_url_extension",
    "format_dashboard",
    "load_config",
    "load_config_with_env_file",
    "load_env_file",
    "normalise_crawl_url",
    "normalise_link_text",
    "normalise_phone_candidate",
    "normalise_column_name",
    "normalise_log_level",
    "normalise_scrape_mode",
    "normalise_text",
    "parse_page",
    "parse_bool",
    "parse_non_negative_int",
    "parse_positive_float",
    "parse_positive_int",
    "print_dashboard",
    "print_demo_dashboard",
    "prioritise_links",
    "read_organisations_csv",
    "read_parsed_organisations_csv",
    "run_demo_export",
    "run_batch_analysis",
    "scrape_dynamic_page",
    "scrape_with_strategy",
    "score_lead",
    "score_link",
    "scrape_page",
    "seconds_to_milliseconds",
    "static_page_appears_insufficient",
    "validate_css_selector",
    "validate_phone_candidate",
    "is_retryable_exception",
]
